[package]
name = "domatt"
version = "0.1.0"
edition = "2021"
authors = ["toadslop <bnheise@gmail.com>"]
readme = "./README.md"
repository = "tbd"
homepage = "tbd"
keywords = ["clayui", "yew", "wasm"]
categories = ["web-programming", "wasm"]
license = "Apache-2.0"
description = "Yew wrapper for Clay Web Components"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = {version = "0.24.1", features = ["derive"]}
